#!/bin/sh
#
# Mock /usr/sbin/sendmail -- just display the message to be sent.
# This is used to avoid emails to be sent by default.
#
# Set variable SENDMAIL_SEND=y to call msmtp for sending it out.
#

# Send everything to stderr
exec 1>&2

if [ "$SENDMAIL_SEND" = "y" ]; then
	/usr/bin/msmtp "$@"
	rc=$?
else
	echo "-------------------------------------------"
	echo "Simulating email delivery. Set SENDMAIL_SEND to \"y\""
	echo "to do actual delivery."
	echo ""
	echo "Command line:"
	echo "  $0 $@"
	echo ""
	echo "Message:"
	cat
	echo "-------------------------------------------"
	rc=0
fi

exit $rc
