#!/bin/sh

cd "$DOCUMENT_ROOT" || exit 1

if [ "$UMASK" != "" ]; then
	umask "$UMASK"
fi

if mountpoint -q .; then
	: "${LOGNAME:=me}"

	GROUP="$(stat --format='%G' .)"
	if [ "$GROUP" = "UNKNOWN" ]; then
		# Mountpoint belongs to a group that does not
		# exist. Create it.
		groupadd --gid "$(stat --format='%g' .)" "$LOGNAME"
		GROUP="$LOGNAME"
	fi

	USER="$(stat --format='%U' .)"
	if [ "$USER" = "UNKNOWN" ]; then
		# User does not exist. Create it.
		useradd --create-home --home-dir /home/me \
			--gid "$GROUP" \
			--no-user-group \
			--shell /bin/bash \
			--uid "$(stat --format='%u' .)" \
				"$LOGNAME"

		echo "$LOGNAME ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/php-tools
		chmod 440 /etc/sudoers.d/php-tools

		USER="$LOGNAME"
	fi
else
	USER="www-data"
fi

exec /sbin/start-stop-daemon --start --exec /bin/bash \
	--chdir "$DOCUMENT_ROOT" --chuid "$USER" --quiet -- -l
