#!/bin/sh

cd "$DOCUMENT_ROOT" || exit 1

if [ "$UMASK" != "" ]; then
	umask "$UMASK"
fi

mnt=$(pwd)
while [ "$mnt" != "" ]; do
	mountpoint -q "$mnt" && break
	mnt="${mnt%/*}"
done

if [ "$mnt" != "" ]; then
	: "${LOGNAME:=me}"

	GROUP="$(stat --format='%G' $mnt)"
	if [ "$GROUP" = "UNKNOWN" ]; then
		# Mountpoint belongs to a group that does not
		# exist. Create it.
		groupadd --gid "$(stat --format='%g' $mnt)" "$LOGNAME"
		GROUP="$LOGNAME"
	fi

	USER="$(stat --format='%U' .)"
	if [ "$USER" = "UNKNOWN" ]; then
		# User does not exist. Create it.
		useradd --create-home --home-dir /home/me \
			--gid "$GROUP" \
			--no-user-group \
			--shell /bin/bash \
			--uid "$(stat --format='%u' $mnt)" \
				"$LOGNAME"

		echo "$LOGNAME ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/php-tools
		chmod 440 /etc/sudoers.d/php-tools

		USER="$LOGNAME"
	fi
else
	USER="www-data"
fi

if [ "$1" = "" ]; then
	COMMAND="/bin/bash"
	set -- "$@"
else
	COMMAND=$(command -v $1)
	if [ "$COMMAND" = "" ]; then
		echo "$1: Command not found" 1>&2
		exit 1
	fi
	shift
fi

exec /sbin/start-stop-daemon --start --exec "$COMMAND" \
	--chdir "$DOCUMENT_ROOT" --chuid "$USER" --quiet -- "$@"
